USE TestTDE;
GO

ALTER DATABASE SET ENCRYPTION SUSPEND;
GO

ALTER DATABASE ENCRYPTION KEY
REGENERATE WITH ALGORITHM = AES_256;
GO

ALTER DATABASE SET ENCRYPTION RESUME;
GO

SELECT * FROM sys.dm_database_encryption_keys;
